server:
  port: 8083
  servlet:
    context-path: /employeeservices
spring:
  application:
    name: ws-employeeservice
  cloud:
    config:
      uri: http://localhost:8082/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
global: 
  name: vijaykumar
